#!/bin/bash

set -u
set -e

directory=./submodules/poa-scripts-moc/generateInitialKey
node_modules=${directory}/node_modules
if [ ! -d ${node_modules} ]; then

	cmd=$(cd ${directory} && npm i --production && node generateInitialKey.js)

else

	cmd2=$(cd ${directory} && npm start)

fi