#!/bin/bash

set -u
set -e

flattener=./node_modules/.bin/poa-solidity-flattener
directory_contracts=contracts
directory_flat=./flat
directory=./submodules/poa-network-consensus-contracts

cmd0=$(cd ${directory} && npm i)
cmd1=$(cd ${directory} && ${flattener} ${directory_contracts}/PoaNetworkConsensus.sol ${directory_flat})
cmd2=$(cd ${directory} && ${flattener} ${directory_contracts}/KeysManager.sol ${directory_flat})
cmd3=$(cd ${directory} && ${flattener} ${directory_contracts}/VotingToChangeKeys.sol ${directory_flat})
cmd4=$(cd ${directory} && ${flattener} ${directory_contracts}/VotingToChangeMinThreshold.sol ${directory_flat})
cmd5=$(cd ${directory} && ${flattener} ${directory_contracts}/ValidatorMetadata.sol ${directory_flat})
cmd6=$(cd ${directory} && ${flattener} ${directory_contracts}/ProxyStorage.sol ${directory_flat})
cmd7=$(cd ${directory} && ${flattener} ${directory_contracts}/VotingToChangeProxyAddress.sol ${directory_flat})
cmd8=$(cd ${directory} && ./node_modules/.bin/truffle compile)