#!/bin/bash
set -u
set -e

source ./scripts/utils.sh

res=$(checkclientversion)

if [ ! -z "$res" -a "$res" != " " ]
then
	echo $res
	exit 1
fi

validator_num=$1

toml=./nodes/parity_validator_${validator_num}/node.toml
log=./nodes/parity_validator_${validator_num}/parity.log

cmd2=$(parity --config $toml > $log > /dev/null 2>&1 &)

exit 0