#!/bin/bash
set -u
set -e

source ./scripts/utils.sh

res=$(checkclientversion)

if [ ! -z "$res" -a "$res" != " " ]
then
	echo $res
	exit 1
fi

toml=./nodes/parity-moc/moc.toml
log=./nodes/parity-moc/parity.log

cmd2=$(parity --config $toml > $log > /dev/null 2>&1 &)

exit 0